
### Create a new permission
POST http://localhost:3000/permission
Content-Type: application/json

{
    "action": "manage",
    "subj": "user"
}


### fetch all permissions
GET http://localhost:3000/permission



### Create a new role
POST http://localhost:3000/role
Content-Type: application/json

{
    "name": "admin",
    "permission": "62319eb896403fab2c50ef7e"
}


### fetch all role
GET http://localhost:3000/role




### Create a new user
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "user one",
    "email": "userone@gmail.com",
    "phone": "01903709156",
    "password": "password",
    "role" : "62319ed296403fab2c50ef80"
}


### fetch all user
GET http://localhost:3000/user


### login a new user
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "userone@gmail.com",
    "password": "password"
}








